function [fig, tiles, keyPressMsg, msg, playAgain] = createGUI(gridSize)
%Creates the GUI objects to display the maze

    %figure to hold the GUI
    fig = figure('Units','pixels',...
            'Position',[600 250 800 800],...
            'Resize','off',...
            'Name','Maze',...
            'MenuBar','none');
    %uipanel in which to draw the tiles of the maze and any
    %buttons/messages
    pan = uipanel('BackgroundColor',[0.8 0.8 1],...
            'BorderType','none');
    %create a Cell Array of tiles 
    tiles = cell(gridSize, gridSize);
    tileLength = 0.9/gridSize;
    for i = 1:gridSize
        for j = 1:gridSize
            xPos = 0.05 + (j-1)*(0.9/gridSize);
            yPos = (i-1)*(0.9/gridSize);
            %index {1,1} is the upper left corner
            tiles{12-i,j} = axes('Color','y',...
                'XTick',[],...
                'Ytick',[],...
                'Units','normalized',...
                'Parent',pan,...
                'Position',[xPos,yPos,tileLength,tileLength],...
                'BoxStyle','back');
        end
    end
    %  create a message area for displaying number of steps taken
    keyPressMsg = uicontrol('Style','text',...
                'Parent',pan,...
                'Units','normalized',...
                'Position',[0.2,0.925,0.2,0.05],...
                'BackgroundColor',[0.8 0.8 1],...
                'String','0',...
                'HorizontalAlignment','center',...
                'FontWeight','bold',...
                'FontSize',20);
    % create a message area to update user with general messages
    msg = uicontrol('Style','text',...
              'Parent',pan,...
              'Units','normalized',...
              'Position',[0.4,0.925,0.2,0.05],...
              'BackgroundColor',[0.8 0.8 1],...
              'String','Good Luck!',...
              'HorizontalAlignment','center',...
              'FontWeight','bold',...
              'FontSize',20);
    % play again button
    playAgain = uicontrol('Style','pushbutton',...
              'Parent',pan,...
              'Units','normalized',...
              'Position',[0.68,0.925,0.2,0.05],...
              'String','Play Again',...
              'enable','off',...
              'callback',(@reset_maze_fcn));
    % area to display orientation arrow
%     arr = imread('upArrow.png');
%     arrow = axes('Parent', pan, ...
%                  'Units', 'normalized', ...
%                  'HandleVisibility','callback', ...
%                  'Position',[0.12 0.91 0.07 0.07]);
%     imshow(arr,'Parent',arrow);
end